name: My First Workflow2
on: push
jobs:
  first_job:
    runs-on:  ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: permission grant
      run: chown +x myscript.sh

    - name: Execute script
      run:  ./myscript.sh

